#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Pykod configuration for eszkoz
# ------------------------------------------------------------
# Description: Auto-generated pykod configuration representing the current system state.
# Generated by: Pykod Configuration Generator
# Date: 2026-01-13 23:42:28
# Host: eszkoz
# License: MIT
# ------------------------------------------------------------

# Import necessary modules from pykod
from pykod import *
from pykod.repositories import AUR, Arch, Flatpak
from pykod.user import (
    GitConfig,
    OpenSSH,
    Program,
    Stow,
    SyncthingConfig,
)

archpkgs = Arch(mirror_url="https://geo.mirror.pkgbuild.com")
aurpkgs = AUR(helper="yay", helper_url="https://aur.archlinux.org/yay.git")
flatpakpkgs = Flatpak(hub_url="flathub")

conf = Configuration(base=archpkgs, dry_run=True, debug=True, verbose=True)

# Disk and partition configuration
conf.devices = Devices(
    disk0=Disk(
        device="/dev/nvme0n1",
        partitions=[
            Partition(name="efi", size="1G", type="esp"),
            Partition(name="swap", size="16G", type="linux-swap"),
            Partition(name="root", size="100%", type="btrfs", mountpoint="/"),
        ],
    ),
)

# Boot configuration
conf.boot = Boot(
    kernel=Kernel(
        package=archpkgs["linux"],
        modules=[
            "btrfs",
            "nvme",
        ],
    ),
    loader=Loader(
        type="systemd-boot",
        timeout=10,
    ),
)

# Locale configuration
conf.locale = Locale(
    default="en_CA.UTF-8 UTF-8",
    additional_locales=[
        "en_US.UTF-8 UTF-8",
    ],
    keymap="us",
    timezone="America/Edmonton",
)

# Network configuration
conf.network = Network(
    hostname="eszkoz",
    settings={"ipv6": True},
)

# Hardware configuration
conf.hardware = Hardware(
    # GPU auto-detection (NEW FEATURE)
    # Automatically detects GPU vendor and installs appropriate drivers
    gpu="auto",  # Options: "auto", "nvidia", "amd", "intel", or None
    gpu_32bit=True,  # Include 32-bit libraries for gaming/Steam
    gpu_extras=True,  # Include extra packages (proprietary alternatives)
    # CPU microcode auto-detection (NEW FEATURE)
    cpu_microcode="auto",  # Options: "auto", "intel", "amd", or None
    # Other hardware components
    audio=archpkgs["pipewire-alsa", "pipewire-pulse"],
    wireless=archpkgs["iw"],
    # Additional hardware components (backward compatible)
    sane=archpkgs["sane", "sane-airscan"],
    printer=archpkgs["gutenprint"],
    power=archpkgs["power-profiles-daemon"],
)

# Desktop environment configuration
conf.desktop = DesktopManager(
    display_manager=Service(package=archpkgs["gdm"]),
    environments={
        "gnome": DesktopEnvironment(
            enable=True,
            package=archpkgs["gnome-shell"],
            extra_packages=archpkgs[
                "gnome-backgrounds",
                "gnome-calculator",
                "gnome-calendar",
                "gnome-characters",
                "gnome-clocks",
                "gnome-color-manager",
                "gnome-connections",
                "gnome-console",
                "gnome-contacts",
                "gnome-control-center",
                "gnome-disk-utility",
                "gnome-font-viewer",
                "gnome-keyring",
                "gnome-logs",
                "gnome-maps",
                "gnome-menus",
                "gnome-music",
                "gnome-remote-desktop",
                "gnome-session",
                "gnome-settings-daemon",
                "gnome-shell-extension-appindicator",
                "gnome-shell-extension-weather-oclock",
                "gnome-software",
                "gnome-system-monitor",
                "gnome-text-editor",
                "gnome-tweaks",
                "gnome-user-share",
                "gnome-weather",
                "xdg-desktop-portal-gnome",
            ]
            + aurpkgs[
                "gnome-shell-extension-arc-menu-git",
                "gnome-shell-extension-blur-my-shell",
                "gnome-shell-extension-dash-to-dock",
                "gnome-shell-extension-gsconnect",
                "gnome-shell-extension-tailscale-qs",
            ],
        ),
        "cosmic": DesktopEnvironment(
            enable=True,
            package=archpkgs["cosmic-session"],
            extra_packages=archpkgs[
                "cosmic-app-library",
                "cosmic-applets",
                "cosmic-bg",
                "cosmic-comp",
                "cosmic-files",
                "cosmic-greeter",
                "cosmic-idle",
                "cosmic-launcher",
                "cosmic-notifications",
                "cosmic-osd",
                "cosmic-panel",
                "cosmic-randr",
                "cosmic-screenshot",
                "cosmic-settings",
                "cosmic-settings-daemon",
                "cosmic-store",
                "cosmic-terminal",
                "cosmic-text-editor",
                "cosmic-wallpapers",
                "cosmic-workspaces",
            ],
        ),
    },
)

# Font configuration
conf.fonts = Fonts(
    font_dir=True,
    packages=archpkgs[
        "adobe-source-serif-fonts",
        "noto-fonts-emoji",
        "ttf-fira-code",
        "ttf-fira-sans",
        "ttf-firacode-nerd",
        "ttf-liberation",
        "ttf-nerd-fonts-symbols",
        "ttf-nerd-fonts-symbols-common",
        "ttf-sourcecodepro-nerd",
        "ttf-ubuntu-font-family",
    ]
    + aurpkgs["ttf-work-sans",],
)

# User configuration
conf.root = User(username="root", no_password=True, shell="/bin/bash")

conf.abuss = User(
    username="abuss",
    name="Antal Buss",
    shell="/usr/bin/zsh",
    groups=["wheel", "audio", "input", "video", "users", "libvirt"],
    allow_sudo=True,
    ssh_authorized=OpenSSH(
        keys=[
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOA6V+TZJ+BmBAU4FB0nbhYQ9XOFZwCHdwXTuQkb77sPi6fVcbzso5AofUc+3DhfN56ATNOOslvjutSPE8kIp3Uv91/c7DE0RHoidNl3oLre8bau2FT+9AUTZnNEtWH/qXp5+fzvGk417mSL3M5jdoRwude+AzhPNXmbdAzn08TMGAkjGrMQejXItcG1OhXKUjqeLmB0A0l3Ac8DGQ6EcSRtgPCiej8Boabn21K2OBfq64KwW/MMh/FWTHndyBF/lhfEos7tGPvrDN+5G05oGjf0fnMOxsmAUdTDbtOTTeMTvDwjJdzsGUluEDbWBYPNlg5wacbimkv51/Bm4YwsGOkkUTy6eCCS3d5j8PrMbB2oNZfByga01FohhWSX9bv35KAP4nq7no9M6nXj8rQVsF0gPndPK/pgX46tpJG+pE1Ul6sSLR2jnrN6oBKzhdZJ54a2wwFSd207Zvahdx3m9JEVhccmDxWltxjKHz+zChAHsqWC9Zcqozt0mDRJNalW8fRXKcSWPGVy1rfbwltiQzij+ChCQQlUG78zW8lU7Bz6FuyDsEFpZSat7jtbdDBY0a4F0yb4lkNvu+5heg+dhlKCFj9YeRDrnvcz94OKvAZW1Gsjbs83n6wphBipxUWku7y86iYyAAYQGKs4jihhYWrFtfZhSf1m6EUKXoWX87KQ== antal.buss@gmail.com",
        ]
    ),
    programs={
        "git": Program(
            enable=True,
            package=archpkgs["git"],
            config=GitConfig(
                {
                    "user.name": "Antal Buss",
                    "user.email": "abuss@example.com",
                    "core.editor": "nano",
                }
            ),
        ),
        "starship": Program(
            enable=True, package=archpkgs["starship"], deploy_config=True
        ),
        "ghostty": Program(
            enable=True, package=archpkgs["ghostty"], deploy_config=True
        ),
        "zsh": Program(enable=True, package=archpkgs["zsh"], deploy_config=True),
        "neovim": Program(enable=True, package=archpkgs["neovim"], deploy_config=True),
        "helix": Program(enable=True, package=archpkgs["helix"], deploy_config=True),
        "emacs": Program(
            enable=True, package=archpkgs["emacs-wayland"], deploy_config=True
        ),
    },
    services={
        "syncthing": Service(
            enable=True,
            package=archpkgs["syncthing"],
        ),
    },
)

# Package configuration
conf.packages = Packages(
    # Arch Linux packages
    archpkgs[
        # Core System
        "pacman-contrib",
        # Development Tools
        "arch-install-scripts",
        "cmake",
        "devtools",
        "gitg",
        "github-cli",
        "lazygit",
        "lldb",
        "meld",
        "ninja",
        # Editors & IDEs
        "vivaldi-ffmpeg-codecs",
        # System Utilities
        "btop",
        "htop",
        "less",
        "libgtop",
        "mc",
        "plocate",
        "qemu-desktop",
        "ripgrep",
        "snapshot",
        "tldr",
        "wget",
        "xdg-desktop-portal-cosmic",
        # Shell & Terminal
        "distrobox",
        "dust",
        "fastfetch",
        "fish",
        "rustup",
        "stow",
        "system-config-printer",
        "wezterm",
        # Network & Communication
        "firefox",
        "thunderbird",
        # Virtualization
        "libvirt",
        "podman",
        # Desktop Environment
        "gnome-shell-extension-weather-oclock",
        # Security & Encryption
        "gvfs-dnssd",
        # File Systems
        "gvfs",
        "gvfs-afc",
        "gvfs-goa",
        "gvfs-google",
        "gvfs-gphoto2",
        "gvfs-mtp",
        "gvfs-nfs",
        "gvfs-onedrive",
        "gvfs-smb",
        "gvfs-wsdd",
        # Languages & Runtimes
        "broot",
        "freecad",
        "go",
        "grilo-plugins",
        "hyperfine",
        "lua",
        "lua-language-server",
        "luarocks",
        "npm",
        "orca",
        "papers",
        "prusa-slicer",
        "pyright",
        "python-lsp-server",
        "remmina",
        "ruff",
        "rygel",
        "xdg-user-dirs-gtk",
        "zig",
        # Other
        "aspell-en",
        "baobab",
        "bind",
        "decibels",
        "dnsmasq",
        "dua-cli",
        "duf",
        "epiphany",
        "flatpak",
        "fwupd",
        "fzf",
        "glow",
        "gping",
        "jujutsu",
        "loupe",
        "lsd",
        "malcontent",
        "nautilus",
        "nix",
        "openscad",
        "showtime",
        "simple-scan",
        "tecla",
        "tmux",
        "uv",
        "vivaldi",
        "yazi",
        "zellij",
        "zoxide",
    ]
    # AUR packages
    + aurpkgs[
        # Browsers
        "brave-bin",
        "min-browser-bin",
        "opera",
        "zen-browser-bin",
        # Development Tools
        "breezy-desktop-gnome-git",
        "c3c-git",
        "c3c-git-debug",
        "claude-code",
        "fresh-editor-bin",
        "fw-ectool-git",
        "fw-ectool-git-debug",
        "fw-fanctrl-git",
        "uemacs-git",
        "uemacs-git-debug",
        "visual-studio-code-bin",
        "visual-studio-code-bin-debug",
        "xr-driver-git",
        "xr-driver-git-debug",
        # Media & Graphics
        "anycubicslicernext-bin-debug",
        # Productivity
        "libpdfium-nojs",
        "libpdfium-nojs-debug",
        "megasync-bin",
        "megasync-bin-debug",
        "rslsync",
        "rslsync-debug",
        # Other
        "botan2",
        "brother-dcp-l2550dw",
        "brother-dcp-l2550dw-debug",
        "duckdb-bin",
        "duckdb-bin-debug",
        "freeimage",
        "libsearpc",
        "libsearpc-debug",
        "ms-365-electron-bin",
        "ms-365-electron-bin-debug",
        "python313-freethreaded-debug",
        "quickemu",
        "seafile",
        "seafile-client-debug",
        "seafile-debug",
        "trayscale-debug",
        "uxplay",
        "uxplay-debug",
        "yay-bin",
        "yay-bin-debug",
    ]
    # Flatpak applications
    + flatpakpkgs[
        # Development
        "com.github.johnfactotum.Foliate",
        "dev.edfloreshz.CosmicTweaks",
        "dev.zed.Zed",
        "io.github.revisto.drum-machine",
        "io.github.softfever.OrcaSlicer",
        "io.github.tobagin.digger",
        "org.onlyoffice.desktopeditors",
        # Media & Entertainment
        "io.freetubeapp.FreeTube",
        "rocks.shy.VacuumTube",
        # Utilities
        "com.mattjakeman.ExtensionManager",
        # GNOME Applications
        "org.gnome.Firmware",
        "org.gnome.World.Citations",
        "org.gnome.World.Iotas",
        # Other
        "com.cherry_ai.CherryStudio",
        "com.jwestall.Forecast",
        "md.obsidian.Obsidian",
        "net.nokyan.Resources",
        "org.zotero.Zotero",
    ]
)

# System services configuration
conf.services = Services(
    {
        "bluetooth": Service(
            enable=True,
            package=archpkgs["bluez"],
        ),
        "cups": Service(
            enable=True,
            package=archpkgs["cups"],
        ),
        "gdm": Service(
            enable=True,
            package=archpkgs["gdm"],
        ),
        "NetworkManager": Service(
            enable=True,
            package=archpkgs["networkmanager"],
        ),
        "sshd": Service(
            enable=True,
            package=archpkgs["openssh"],
        ),
        "systemd-timesyncd": Service(
            enable=True,
        ),
        "tailscaled": Service(
            enable=True,
            package=archpkgs["tailscale"],
        ),
    }
)

if __name__ == "__main__":
    from pykod.cli import run

    run(conf)
