# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# Pykod configuration for the current system
# ------------------------------------------------------------
# Description: This file was generated by pykod and represents the current system configuration.
# Author: Pykod Agent
# Date: 2026-01-12
# License: MIT
# Notes: This configuration represents the current system state including:
#        - NVMe disk with UEFI boot partition, swap, and btrfs root
#        - GNOME and Cosmic desktop environments
#        - Current package installations from pacman, AUR, and Flatpak
#        - Enabled system services
#        - User configuration for 'abuss'
# ------------------------------------------------------------

# Import necessary modules from pykod
from pykod import *
from pykod.repositories import AUR, Arch, Flatpak
from pykod.user import (
    GitConfig,
    OpenSSH,
    Program,
    Stow,
    SyncthingConfig,
)

archpkgs = Arch(mirror_url="https://mirror.rackspace.com/archlinux")
aurpkgs = AUR(helper="paru", helper_url="https://aur.archlinux.org/paru.git")
flatpakpkgs = Flatpak(hub_url="flathub")

conf = Configuration(base=archpkgs, dry_run=True, debug=True, verbose=True)

# Disk and partition configuration based on current system layout
conf.devices = Devices(
    disk0=Disk(
        device="/dev/nvme0n1",
        partitions=[
            Partition(name="efi", size="1G", type="esp", mountpoint="/boot"),
            Partition(name="swap", size="16G", type="linux-swap"),
            Partition(name="root", size="100%", type="btrfs", mountpoint="/"),
        ],
    ),
)

# Boot configuration
conf.boot = Boot(
    kernel=Kernel(
        package=archpkgs["linux"],
        modules=[
            "nvme",
            "btrfs",
        ],
    ),
    loader=Loader(
        type="systemd-boot",
        timeout=10,
    ),
)

# Locale configuration based on current system settings
conf.locale = Locale(
    default="en_CA.UTF-8 UTF-8",
    additional_locales=[
        "en_US.UTF-8 UTF-8",
    ],
    keymap="us",
    timezone="America/Edmonton",
)

# Network configuration
conf.network = Network(
    hostname="eszkoz",
    settings={"ipv6": True},
)

# Desktop environment configuration
conf.desktop = DesktopManager(
    display_manager=Service(package=archpkgs["gdm"]),
    environments={
        "gnome": DesktopEnvironment(
            enable=True,
            package=archpkgs["gnome-shell"],
            extra_packages=archpkgs[
                "gnome-control-center",
                "gnome-tweaks",
                "gnome-shell-extension-appindicator",
                "gnome-shell-extension-weather-oclock",
                "nautilus",
                "gnome-calculator",
                "gnome-calendar",
                "gnome-characters",
                "gnome-clocks",
                "gnome-color-manager",
                "gnome-connections",
                "gnome-console",
                "gnome-contacts",
                "gnome-disk-utility",
                "gnome-font-viewer",
                "gnome-keyring",
                "gnome-logs",
                "gnome-maps",
                "gnome-music",
                "gnome-remote-desktop",
                "gnome-session",
                "gnome-settings-daemon",
                "gnome-software",
                "gnome-system-monitor",
                "gnome-text-editor",
                "gnome-user-share",
                "gnome-weather",
                "gnome-backgrounds",
            ]
            + aurpkgs[
                "gnome-shell-extension-arc-menu-git",
                "gnome-shell-extension-blur-my-shell",
                "gnome-shell-extension-dash-to-dock",
                "gnome-shell-extension-gsconnect",
                "gnome-shell-extension-tailscale-qs",
            ],
        ),
        "cosmic": DesktopEnvironment(
            enable=True,
            package=archpkgs["cosmic-session"],
            extra_packages=archpkgs[
                "cosmic-app-library",
                "cosmic-applets",
                "cosmic-bg",
                "cosmic-comp",
                "cosmic-files",
                "cosmic-greeter",
                "cosmic-idle",
                "cosmic-launcher",
                "cosmic-notifications",
                "cosmic-osd",
                "cosmic-panel",
                "cosmic-randr",
                "cosmic-screenshot",
                "cosmic-settings",
                "cosmic-settings-daemon",
                "cosmic-store",
                "cosmic-terminal",
                "cosmic-text-editor",
                "cosmic-wallpapers",
                "cosmic-workspaces",
                "xdg-desktop-portal-cosmic",
            ],
        ),
    },
)

# Font configuration
conf.fonts = Fonts(
    font_dir=True,
    packages=archpkgs[
        "adobe-source-serif-fonts",
        "ttf-fira-code",
        "ttf-fira-sans",
        "ttf-firacode-nerd",
        "ttf-liberation",
        "ttf-nerd-fonts-symbols",
        "ttf-nerd-fonts-symbols-common",
        "ttf-sourcecodepro-nerd",
        "ttf-ubuntu-font-family",
        "noto-fonts-emoji",
    ]
    + aurpkgs["ttf-work-sans"],
)

# Root user configuration
conf.root = User(username="root", no_password=True, shell="/bin/bash")

# Main user configuration
conf.abuss = User(
    username="abuss",
    name="Antal Buss",
    shell="/usr/bin/zsh",
    groups=["audio", "input", "users", "video", "wheel"],
    allow_sudo=True,
    ssh_authorized=OpenSSH(
        keys=[
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOA6V+TZJ+BmBAU4FB0nbhYQ9XOFZwCHdwXTuQkb77sPi6fVcbzso5AofUc+3DhfN56ATNOOslvjutSPE8kIp3Uv91/c7DE0RHoidNl3oLre8bau2FT+9AUTZnNEtWH/qXp5+fzvGk417mSL3M5jdoRwude+AzhPNXmbdAzn08TMGAkjGrMQejXItcG1OhXKUjqeLmB0A0l3Ac8DGQ6EcSRtgPCiej8Boabn21K2OBfq64KwW/MMh/FWTHndyBF/lhfEos7tGPvrDN+5G05oGjf0fnMOxsmAUdTDbtOTTeMTvDwjJdzsGUluEDbWBYPNlg5wacbimkv51/Bm4YwsGOkkUTy6eCCS3d5j8PrMbB2oNZfByga01FohhWSX9bv35KAP4nq7no9M6nXj8rQVsF0gPndPK/pgX46tpJG+pE1Ul6sSLR2jnrN6oBKzhdZJ54a2wwFSd207Zvahdx3m9JEVhccmDxWltxjKHz+zChAHsqWC9Zcqozt0mDRJNalW8fRXKcSWPGVy1rfbwltiQzij+ChCQQlUG78zW8lU7Bz6FuyDsEFpZSat7jtbdDBY0a4F0yb4lkNvu+5heg+dhlKCFj9YeRDrnvcz94OKvAZW1Gsjbs83n6wphBipxUWku7y86iYyAAYQGKs4jihhYWrFtfZhSf1m6EUKXoWX87KQ== antal.buss@gmail.com"
        ]
    ),
    programs={
        "git": Program(
            enable=True,
            package=archpkgs["git"],
            config=GitConfig(
                {
                    "user.name": "Antal Buss",
                    "user.email": "antal.buss@gmail.com",
                    "core.editor": "helix",
                }
            ),
        ),
        "starship": Program(
            enable=True, package=archpkgs["starship"], deploy_config=True
        ),
        "ghostty": Program(
            enable=True, package=archpkgs["ghostty"], deploy_config=True
        ),
        "zsh": Program(enable=True, package=archpkgs["zsh"], deploy_config=True),
        "neovim": Program(enable=True, package=archpkgs["neovim"], deploy_config=True),
        "helix": Program(enable=True, package=archpkgs["helix"], deploy_config=True),
        "emacs": Program(
            enable=True,
            package=archpkgs["emacs-wayland"],
            deploy_config=True,
            extra_packages=archpkgs["aspell-en"],
        ),
    },
    services={
        "syncthing": Service(
            enable=True,
            package=archpkgs["syncthing"],
        ),
    },
)

# Package configuration based on current system
conf.packages = Packages(
    # Core system packages
    archpkgs[
        "base",
        "base-devel",
        "linux",
        "linux-firmware",
        "amd-ucode",
        "sudo",
        # Development tools
        "git",
        "github-cli",
        "go",
        "rustup",
        "python-lsp-server",
        "pyright",
        "lua-language-server",
        "cmake",
        "ninja",
        "devtools",
        "arch-install-scripts",
        "ruff",
        "uv",
        "zig",
        # Editors
        "neovim",
        "emacs-wayland",
        "helix",
        # System utilities
        "htop",
        "btop",
        "mc",
        "less",
        "stow",
        "tmux",
        "zellij",
        "pacman-contrib",
        "plocate",
        "bind",
        "wget",
        "whois",
        # Shell and terminal
        "zsh",
        "fish",
        "bash-completion",
        "starship",
        "ghostty",
        "fzf",
        "ripgrep",
        "broot",
        "duf",
        "dust",
        "dua-cli",
        "lsd",
        "tldr",
        "glow",
        "hyperfine",
        "gping",
        "fastfetch",
        "zoxide",
        "yazi",
        # Network and services
        "networkmanager",
        "openssh",
        "tailscale",
        "dnsmasq",
        # Audio and video
        "pipewire-alsa",
        "pipewire-pulse",
        # Bluetooth
        "bluez",
        # Printing and scanning
        "cups",
        "gutenprint",
        "sane",
        "sane-airscan",
        "system-config-printer",
        # Storage and filesystems
        "btrfs-progs",
        # Virtualization and containers
        "qemu-desktop",
        "libvirt",
        "podman",
        "distrobox",
        # Applications
        "firefox",
        "thunderbird",
        "freecad",
        "openscad",
        "prusa-slicer",
        "remmina",
        "papers",
        "meld",
        "gitg",
        # GNOME applications
        "baobab",
        "decibels",
        "epiphany",
        "loupe",
        "simple-scan",
        "snapshot",
        "malcontent",
        "orca",
        "rygel",
        "grilo-plugins",
        "showtime",
        "tecla",
        # Storage
        "gvfs",
        "gvfs-afc",
        "gvfs-dnssd",
        "gvfs-goa",
        "gvfs-google",
        "gvfs-gphoto2",
        "gvfs-mtp",
        "gvfs-nfs",
        "gvfs-onedrive",
        "gvfs-smb",
        "gvfs-wsdd",
        # Other system tools
        "fwupd",
        "power-profiles-daemon",
        "libgtop",
        "iw",
        "flatpak",
        "xdg-user-dirs-gtk",
        # Build tools and languages
        "lua",
        "luarocks",
        "npm",
        "lldb",
        # Additional utilities
        "lazygit",
        "jujutsu",
        "schroot",
        "dracut",
        "nix",
        # Terminal utilities
        "wezterm",
    ]
    # AUR packages
    + aurpkgs[
        "visual-studio-code-bin",
        "brave-bin",
        "opera",
        "vivaldi",
        "vivaldi-ffmpeg-codecs",
        "zen-browser-bin",
        "yay-bin",
        "megasync-bin",
        "quickemu",
        "uxplay",
        "min-browser-bin",
        "ms-365-electron-bin",
        "rslsync",
        "brother-dcp-l2550dw",
        "fw-fanctrl-git",
        "fresh-editor-bin",
        "duckdb-bin",
        "c3c-git",
        "claude-code",
        "uemacs-git",
        "breezy-desktop-gnome-git",
    ]
    # Flatpak packages
    + flatpakpkgs[
        "com.calibre_ebook.calibre",
        "com.cherry_ai.CherryStudio",
        "com.github.johnfactotum.Foliate",
        "com.jwestall.Forecast",
        "com.mattjakeman.ExtensionManager",
        "dev.edfloreshz.CosmicTweaks",
        "dev.zed.Zed",
        "io.freetubeapp.FreeTube",
        "io.github.revisto.drum-machine",
        "io.github.softfever.OrcaSlicer",
        "io.github.tobagin.digger",
        "md.obsidian.Obsidian",
        "net.nokyan.Resources",
        "org.gnome.Firmware",
        "org.gnome.World.Citations",
        "org.gnome.World.Iotas",
        "org.onlyoffice.desktopeditors",
        "org.zotero.Zotero",
        "rocks.shy.VacuumTube",
    ]
)

# System services configuration
conf.services = Services(
    {
        "networkmanager": Service(
            enable=True,
            package=archpkgs["networkmanager"],
            service_name="NetworkManager",
        ),
        "bluetooth": Service(
            enable=True, package=archpkgs["bluez"], service_name="bluetooth"
        ),
        "cups": Service(
            enable=True,
            package=archpkgs["cups"],
            extra_packages=archpkgs["gutenprint"] + aurpkgs["brother-dcp-l2550dw"],
        ),
        "avahi": Service(
            enable=True, package=archpkgs["avahi"], service_name="avahi-daemon"
        ),
        "openssh": Service(
            enable=True,
            package=archpkgs["openssh"],
            service_name="sshd",
        ),
        "tailscale": Service(
            enable=True, package=archpkgs["tailscale"], service_name="tailscaled"
        ),
        "timesyncd": Service(enable=True, service_name="systemd-timesyncd"),
        "fwupd": Service(enable=True, package=archpkgs["fwupd"]),
    }
)

if __name__ == "__main__":
    from pykod.cli import run

    run(conf)
